repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-docstring-first
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: check-json
      files: \.(json)$
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5
  hooks:
   - id: autopep8
     args: ["--global-config=.autopep8", "--in-place", "--verbose", "--aggressive", "--aggressive"]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.0.1
  hooks:
    - id: add-trailing-comma
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.8.0
  hooks:
    - id: reorder-python-imports
      args: [--py3-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.2
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.761
  hooks:
    - id: mypy
